# https://github.com/lanagarmire/deepimpute/blob/master/Dockerfile

FROM tensorflow/tensorflow

MAINTAINER Levi Mangarin "markmangarin@gmail.com"

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/lanagarmire/deepimpute && cd deepimpute && pip install --user .
