FROM ubuntu:16.04
MAINTAINER Levi Mangarin "markmangarin@gmail.com"

################################################################################
# Install all the necessary software
################################################################################
# Python, R, Java 8, other dependencies (gcc)
## Basic image utilities
### software-properties-common is for add-apt repository, coreutils for cut, open-ssh-client for scp
RUN apt-get update \
    && apt-get install -y --force-yes software-properties-common \
    && echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | tee -a /etc/apt/sources.list \
    && gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9 \
    && gpg -a --export E084DAB9 | apt-key add - \
    && add-apt-repository ppa:openjdk-r/ppa \
    && apt-get update \
    && apt-get clean \
    && apt-get install -qqy software-properties-common git wget curl openssh-client unzip vim gcc gawk sed coreutils sudo net-tools r-base r-base-dev openjdk-8-jdk openjdk-7-jdk zlib1g-dev libncursesw5-dev libncurses5-dev maven g++ zlib1g-dev build-essential gcc python-setuptools python-dev python3-docutils python3-flask python3-pip python python2.7 gcc tabix libz-dev vcftools libcurl4-openssl-dev libssl-dev \
    && easy_install pip \
    && pip install numpy

RUN apt-get update --fix-missing

### Install CMake
RUN sudo add-apt-repository ppa:george-edison55/cmake-3.x \
    && sudo apt-get update \
    && sudo apt-get install -qqy cmake

################################################################################
### Install Tree reconstruction scripts
ADD scripts/ /scripts/
ADD scripts/dispatcher.sh /scripts/dispatcher.sh
ADD scripts/run_phylogeny.sh /scripts/run_phylogeny.sh
RUN chmod u+x /scripts/dispatcher.sh \
        && chmod u+x /scripts/run_phylogeny.sh

### Install PhyloWGS dependencies
# Python2 + libs
RUN pip2 install --upgrade pip 
RUN pip2 install numpy
RUN pip2 install scipy
RUN pip2 install ete2
RUN pip2 install pyvcf
RUN pip2 install argparse

# GSL
RUN apt-get install -qqy gsl-bin libgsl0-dev gsl-doc-info gsl-doc-pdf gsl-ref-html gsl-ref-psdoc

# Compile PhyloWGS
RUN cd /scripts/phylowgs-master/ \
        &&  g++ -o mh.o -O3 mh.cpp  util.cpp `gsl-config --cflags --libs`

################################################################################
# Configure the image

## Set environment variables
ENV HOME /root

################################################################################
# List filetree before execution
WORKDIR /
RUN ls -alR | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/' > filetree_origin.txt
