FROM ubuntu:16.04
MAINTAINER Levi Mangarin "markmangarin@gmail.com"

################################################################################
# Install all the necessary software
################################################################################
# Python, R, Java 8, other dependencies
## Basic image utilities
### software-properties-common is for add-apt repository, coreutils for cut, open-ssh-client for scp
RUN apt-get update \
    && apt-get install -y --force-yes software-properties-common \
    && echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | tee -a /etc/apt/sources.list \
    && gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9 \
    && gpg -a --export E084DAB9 | apt-key add - \
    && add-apt-repository ppa:openjdk-r/ppa \
    && apt-get update \
    && apt-get clean \
    && apt-get install -qqy software-properties-common git wget curl openssh-client unzip vim gawk sed coreutils sudo net-tools r-base r-base-dev openjdk-8-jdk openjdk-7-jdk zlib1g-dev libncursesw5-dev libncurses5-dev maven g++ zlib1g-dev build-essential python-setuptools python-dev python3-docutils python3-flask python3-pip python tabix vim \
    && easy_install pip \
    && pip install numpy 

RUN apt-get update --fix-missing

### Install CMake
RUN sudo add-apt-repository ppa:george-edison55/cmake-3.x \
    && sudo apt-get update \
    && sudo apt-get install -qqy cmake

################################################################################
### Install fastqc
RUN cd / && \
    wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip && \
    unzip fastqc_v0.11.5.zip && \
    cd FastQC/ && \
    chmod 755 fastqc

### Install samtools
RUN cd / && \
    wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 && \
    bunzip2 samtools-1.3.1.tar.bz2 && \
    tar -xvf samtools-1.3.1.tar && \
    cd samtools-1.3.1 && \
    make
################################################################################
# RNA tools
### Install STAR
RUN wget https://github.com/alexdobin/STAR/archive/2.6.0a.tar.gz \
    && tar -zxvf 2.6.0a.tar.gz \
    && cd STAR-2.6.0a/source \
    && make STAR \
    && file STAR

### Install HTSeq
RUN wget https://pypi.python.org/packages/source/H/HTSeq/HTSeq-0.9.1.tar.gz \
    && tar -zxvf HTSeq-0.9.1.tar.gz \
    && cd HTSeq-0.9.1/ \
    && python setup.py install --user \
    && chmod +x scripts/htseq-count

### Install featureCounts (taken from https://github.com/GrosseLab/InstallProcedures/blob/master/subread_1.5.1.sh)
RUN cd / \
    && wget -O subread-1.5.1-source.tar.gz 'http://downloads.sourceforge.net/project/subread/subread-1.5.1/subread-1.5.1-source.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fsubread%2Ffiles%2Fsubread-1.5.1%2F&ts=1476683757&use_mirror=vorboss' \
    && tar xvzf subread-1.5.1-source.tar.gz \
    && rm subread-1.5.1-source.tar.gz \
    && cd subread-1.5.1-source/src \
    && make -f Makefile.Linux \
    && cd ../.. \
    && mv subread-1.5.1-source /usr/local/bin/subread-1.5.1 \
    && ln -sf /usr/local/bin/subread-1.5.1/bin/* /usr/local/bin/

################################################################################
# Configure the image
## Clone the most recent version of the pipeline and create project directories
################################################################################
WORKDIR /

RUN git clone https://github.com/levvim/ds_pipeline.git /ds_pipeline && \
        mkdir PROJECT && \
        cd PROJECT && \
        mkdir raw complete

## Set environment variables
ENV HOME /root
ENV WORK_DIR /home/user/PROJECT/
ENV PATH="/samtools-1.3.1:/bam-readcount/bin:/bowtie2-2.2.9:/tophat-2.1.1.Linux_x86_64:/STAR-2.5.1b/source:/cufflinks-2.2.1.Linux_x86_64:/HTSeq-0.6.1p1/scripts:/FastQC:/picard-tools-1.140:/samstat-1.5.1/src:/cromwell:/flexbar_v2.4_linux64:/kallisto/build/src:/sortmerna:/trimmomatic:/hisat2-2.0.4:/usr/local/bin:${PATH}"
ENV PYTHONPATH="${PYTHONPATH}:/HTSeq-0.6.1p1/scripts"
#
################################################################################
# Import any additional data
## Import necessary reference files


################################################################################
# List filetree before execution
WORKDIR /
RUN ls -alR | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/' > filetree_origin.txt
