FROM ubuntu:16.04
MAINTAINER Levi Mangarin "markmangarin@gmail.com"

################################################################################
# Install all the necessary software
################################################################################
# Python, R, Java 8, other dependencies
## Basic image utilities
### software-properties-common is for add-apt repository, coreutils for cut, open-ssh-client for scp
RUN apt-get update \
    && apt-get install -y --force-yes software-properties-common \
    && echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | tee -a /etc/apt/sources.list \
    && apt-get update \
    && apt-get clean \
    && apt-get install -qqy --allow-unauthenticated software-properties-common git wget curl openssh-client unzip vim gcc gawk sed coreutils sudo net-tools zlib1g-dev libncursesw5-dev libncurses5-dev maven g++ zlib1g-dev build-essential gcc python-setuptools python-dev python3-docutils python3-flask python3-pip python tabix libz-dev vcftools libcurl4-openssl-dev libssl-dev \
    && easy_install pip \
    && pip install CITE-seq-Count

################################################################################
# Configure the image
################################################################################
WORKDIR /

################################################################################
# Import any additional data

################################################################################
# List filetree before execution
WORKDIR /
RUN ls -alR | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/' > filetree_origin.txt
